server:
  port: 9000
          com:    ibm:      routes: 
       - id: loginMicroservice              
        uri: http://localhost:9002/        
        predicates:
        - Path=/ecommerce/login/**          
        
       
      - id: orderMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerceV2/**

        
      - id: orderMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerce/** 
        filters:
        - RewritePath=/ecommerce, /ecommerceV2/
        
        